### PR TITLE
Overlapping of cards fixed

### PR DESCRIPTION
**Pull request by priyanshu6781**

### CODE REVIEW

**Review by rohitgulam — CHANGES_REQUESTED** [review]
Judith's and Edson's cards are working properly. But there's still a problem with Vaileth's. 

Can you arrange it accordingly?  Also, can you fix the comments too so that they are arranged properly?

**Comment by priyanshu6781** [comment]
Okay, got it!!

**Comment by priyanshu6781** [comment]
Hey, can you please what tell what to fix in Valieth's card. Because in my pc it is not overlapping and working fine.
Screenshot 2022-10-10 140424

**Comment by rohitgulam** [comment]
Right there on the social icons, there's an image tag but currently not displaying. It displays only the alt. 

Also can you send a screenshot of the the last two cards.

**Comment by priyanshu6781** [comment]
Okay then I should comment out that image tag as it is not there in the rest of the cards.

Sure I'm attaching the screenshot.
Screenshot 2022-10-10 183454

**Comment by rohitgulam** [comment]
I think it's better to delete it altogether. Can I see the code on Vaileth's card? (Attach screenshot)

**Comment by priyanshu6781** [comment]
Yeah, here it is
Screenshot 2022-10-10 190538

**Comment by rohitgulam** [comment]
Yeah just delete it but take that image source and make it as image source for Edson's card. After this everything everything will be alright

**Comment by priyanshu6781** [comment]
Okay, will do so

**Comment by priyanshu6781** [comment]
**But doing so is again displaying the alt value**
image
**This is what that image looks like. Clearly it's not the image of Edson**
296285011_601561774979256_3197983523861710170_n

**Can you please provide me the image link of Edson**

**Comment by rohitgulam** [comment]
It seems that Edison added that image from his Instagram account which displays that blue image. Can you make it so that the blue image display?

**Comment by priyanshu6781** [comment]
Hey, @rohitgulam its done

**Comment by rohitgulam** [comment]
We aren't supposed to add images in this repo. Can you use the link but still make the image show? If it's not possible, just put back the link even if it's not showing and delete the images files (asset folder and image file)

**Comment by priyanshu6781** [comment]
Okay, so I've deleted that asset folder and put the link back.

**Review by rohitgulam — APPROVED** [review]
Awesome! You did a great job!

**Pull request merged**
